version: "2"

run:
  timeout: 5m
  go: "1.22"

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - unconvert
    - gocyclo
    - bodyclose
  settings:
    errcheck:
      check-type-assertions: true
      check-blank: true
    govet:
      enable-all: true
      disable:
        - fieldalignment
    misspell:
      locale: US
  exclusions:
    rules:
      - path: _test\.go
        linters:
          - errcheck
      - path: tests/
        linters:
          - errcheck
      - path: internal/database/migrate\.go
        text: "Error return value of `m.Close` is not checked"
        linters:
          - errcheck

formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/searchandrescuegg/rescuestream-api
